# Generated by Django 3.1.4 on 2021-01-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210112_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_day',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
