# Generated by Django 3.1.4 on 2021-02-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20210112_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='membership',
            field=models.CharField(default='Normal', max_length=10),
        ),
    ]
